### ISSUE TITLE
[Tile Fall] Internal Error: -2 (KErrInvalidArgs)

### ISSUE THREAD

**Issue by kapfab** [inseven/opolua#449]
## Description

Error occurs when using the `Tools>Preferences…` menu option (or the `Game prefs` toolbar button).

## Metadata

| Key | Value |
| --- | --- |
| **Title** | Tile Fall |
| **Source URL** | https://archive.org/download/3-libjune-05/3LIBJUNE05.iso/library%2Fepocgames%2Ftilefall%2FTileFall.SIS |

## Details

```
-2 (KErrInvalidArgs)
TILEFALL\DOPREFS:00002255: 57 [CallFunction] 0x37 (Dialog)
TILEFALL\KEYPRESS:00003134: 53 [RunProcedure] 0x0054 (name="DOPREFS" nargs=0)
TILEFALL\PLAY:00002961: 53 [RunProcedure] 0x0047 (name="KEYPRESS" nargs=1)
TILEFALL\MAIN:00000618: 53 [RunProcedure] 0x03F2 (name="PLAY" nargs=0)
TOOLBAR\TBARLINK: [Lua] modules/toolbar.lua:84
TILEFALL\START:00000072: 53 [RunProcedure] 0x0012 (name="TBARLINK" nargs=1)
stack traceback:
	[C]: in function 'error'
	dialog.lua:1502: in method 'init'
	dialog.lua:2296: in function <dialog.lua:2254>
	(...tail calls...)
	fns.lua:690: in function 'fns.Dialog'
	ops.lua:1032: in function 'ops.CallFunction'
	runtime.lua:899: in function <runtime.lua:884>
	[C]: in function 'xpcall'
	runtime.lua:1018: in method 'pcallProc'
	runtime.lua:1064: in method 'callProc'
	modules/toolbar.lua:84: in field 'fn'
	runtime.lua:301: in method 'pushNewFrame'
	ops.lua:1002: in function 'ops.RunProcedure'
	runtime.lua:899: in function <runtime.lua:884>
	[C]: in function 'xpcall'
	runtime.lua:1018: in method 'pcallProc'
	runtime.lua:1305: in function 'runtime.runOpo'
```

**Comment by tomsci** [comment]
@kapfab It might be worth reinstalling Tile Fall because I think there were some mismatched expectations about colour support that could lead to some apps deleting the wrong resources but then trying to use them.

Also, I just fixed a pretty major bug in string comparisons that could lead to who knows what problems depending on the locale of your system, so retesting with latest build would also be worthwhile.

Failing that, I can add some debug to the dialog API so we can see exactly what's going wrong.

**Comment by kapfab** [comment]
I reinstalled the app (it’s all in German now!) and I still get the same issue on iOS (and it still works fine on macOS).

**Comment by tomsci** [comment]
It still doesn't reproduce for me :(

<img width="779" height="539" alt="Image" src="https://github.com/user-attachments/assets/7f3a45dd-770f-4f4f-b87e-acfee34a573f" />

...Later...

Hmm OK if I install it through the iOS app (I took a shortcut and installed from the Qt app for the previous screenshot) I get an empty tile set choice list which (for my current checkout) doesn't error on dialog launch but does when I try and open the choice list. Seems likely this is the same root cause although I'm not sure why it doesn't reproduce exactly the same way:

<img width="1334" height="750" alt="Image" src="https://github.com/user-attachments/assets/ccaa3cef-f51f-4c6e-9cf0-0692dfd11c67" />

**Comment by jbmorley** [comment]
> best guess is might've been GemTile which makes requests for "something.wav " (with a space on the end)

That does sound familiar...

**Comment by tomsci** [comment]
After updating to a build with the fix in, you'll need to uninstall Tile Fall and reinstall it, in order for the fix to take effect (or manually find the `"*.tse"` files and rename them `"*.tset"`)
